name: vaden_security
description: A Dart package for security-related functionalities. Vaden is a Backend Framework Using Dart.
version: 0.0.1
repository: https://github.com/Flutterando/vaden

resolution: workspace

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  vaden:
  dart_jsonwebtoken: ^3.2.0
  bcrypt: ^1.1.3
  collection: ^1.19.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
